create table "public"."article_summaries" (
    "id" bigint generated by default as identity not null,
    "article_url" text not null,
    "summary" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."article_summaries" enable row level security;

CREATE UNIQUE INDEX article_summaries_article_url_key ON public.article_summaries USING btree (article_url);

CREATE UNIQUE INDEX article_summaries_pkey ON public.article_summaries USING btree (id);

alter table "public"."article_summaries" add constraint "article_summaries_pkey" PRIMARY KEY using index "article_summaries_pkey";

alter table "public"."article_summaries" add constraint "article_summaries_article_url_key" UNIQUE using index "article_summaries_article_url_key";

alter table "public"."bookmarked_articles" add constraint "bookmarked_articles_url_fkey" FOREIGN KEY (url) REFERENCES article_summaries(article_url) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."bookmarked_articles" validate constraint "bookmarked_articles_url_fkey";

grant delete on table "public"."article_summaries" to "anon";

grant insert on table "public"."article_summaries" to "anon";

grant references on table "public"."article_summaries" to "anon";

grant select on table "public"."article_summaries" to "anon";

grant trigger on table "public"."article_summaries" to "anon";

grant truncate on table "public"."article_summaries" to "anon";

grant update on table "public"."article_summaries" to "anon";

grant delete on table "public"."article_summaries" to "authenticated";

grant insert on table "public"."article_summaries" to "authenticated";

grant references on table "public"."article_summaries" to "authenticated";

grant select on table "public"."article_summaries" to "authenticated";

grant trigger on table "public"."article_summaries" to "authenticated";

grant truncate on table "public"."article_summaries" to "authenticated";

grant update on table "public"."article_summaries" to "authenticated";

grant delete on table "public"."article_summaries" to "service_role";

grant insert on table "public"."article_summaries" to "service_role";

grant references on table "public"."article_summaries" to "service_role";

grant select on table "public"."article_summaries" to "service_role";

grant trigger on table "public"."article_summaries" to "service_role";

grant truncate on table "public"."article_summaries" to "service_role";

grant update on table "public"."article_summaries" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."article_summaries"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."article_summaries"
as permissive
for select
to public
using (true);